# Generated by Django 6.0.5 on 2026-06-23 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('spotify_id', models.CharField(blank=True, max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('image_url', models.URLField(blank=True, max_length=512)),
                ('genres', models.TextField(blank=True, help_text='Comma-separated genres')),
                ('popularity', models.IntegerField(default=0)),
                ('time_range', models.CharField(default='medium_term', max_length=16)),
                ('rank', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='spotify_data.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('artist_name', models.CharField(max_length=256)),
                ('album_name', models.CharField(blank=True, max_length=256)),
                ('album_image_url', models.URLField(blank=True, max_length=512)),
                ('duration_ms', models.IntegerField(default=0)),
                ('time_range', models.CharField(default='medium_term', max_length=16)),
                ('rank', models.IntegerField(default=0)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='spotify_data.analysissession')),
            ],
        ),
    ]
